spring.application.name=BankingApplication

spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/project

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.issuer=${OWNER}
jwt.expiry=900
jwt.refresh-expiry=604800