package com.securebank.enums;

public enum KYCRejectionReason {

	NAME_MISMATCH, DOB_MISMATCH, PAN_DETAILS_MISMATCH, AADHAAR_DETAILS_MISMATCH, DOCUMENT_NOT_CLEAR, DOCUMENT_MISSING,
	DUPLICATE_KYC, OTHER
}
